---
name: Net-IDN-Encode
version: 1.000
author:
  - 'Claus Färber <CFAERBER@cpan.org>'
abstract: Internationalizing Domain Names in Applications (RFC 3490)
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
  Test::NoWarnings: 0
requires:
  Net::IDN::Nameprep: 1
configure_requires:
  Module::Build: 0.35
provides:
  Net::IDN::Encode:
    file: lib/Net/IDN/Encode.pm
    version: 1.000
  Net::IDN::Punycode:
    file: lib/Net/IDN/Punycode.pm
    version: 1.000
  Net::IDN::Punycode::PP:
    file: lib/Net/IDN/Punycode/PP.pm
    version: 1.000
no_index:
  directory: eg
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
