---
name: Net-IDN-Encode
version: 0.99_20091231
author:
  - 'Claus Färber <CFAERBER@cpan.org>'
abstract: Internationalizing Domain Names in Applications (S<RFC 3490>)
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
  Test::NoWarnings: 0
requires:
  Unicode::Stringprep: 1
  perl: 5.008003
configure_requires:
  Module::Build: 0.35
provides:
  IDNA::Punycode:
    file: lib/IDNA/Punycode.pm
    version: 0.99_20091231
  Net::IDN::Encode:
    file: lib/Net/IDN/Encode.pm
    version: 0.99_20091231
  Net::IDN::Nameprep:
    file: lib/Net/IDN/Nameprep.pm
    version: 0.99_20091231
  Net::IDN::Punycode:
    file: lib/Net/IDN/Punycode.pm
    version: 0.99_20091231
no_index:
  directory: eg
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
