---
abstract: 'Internationalizing Domain Names in Applications (RFC 3490)'
author:
  - 'Claus Färber <CFAERBER@cpan.org>'
build_requires:
  ExtUtils::CBuilder: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-IDN-Encode
no_index:
  directory: eg
provides:
  Net::IDN::Encode:
    file: lib/Net/IDN/Encode.pm
    version: 1.100
  Net::IDN::Punycode:
    file: lib/Net/IDN/Punycode.pm
    version: 1.000
  Net::IDN::Punycode::PP:
    file: lib/Net/IDN/Punycode/PP.pm
    version: 1.000
requires:
  Net::IDN::Nameprep: 1.1
resources:
  license: http://dev.perl.org/licenses/
version: 1.100
